### ISSUE TITLE
Pre-Wrap in tooltips

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/tolmea#21]
I just noticed that the tooltips don't allow the whitespace pre-wrap. Is there a way to quickly add that into the tooltip or is it too much time for not enough benefit?

**Comment by Tyroche** [comment]
I think putting the pre-wrap style in the template should do it.

I just tested it and I think that's what you want!  
I'll push a quick change for you, and you can let me know if that works.

**Comment by Tyroche** [comment]
Pushed.  Lmk whenever :)
