### ISSUE TITLE
Enhance /roll action security [Feature Request]

### ISSUE THREAD

**Issue by mlapaglia** [etkirsch/tolmea#27]
Currently the /roll command generates text similar to the /me command. It is trivial for a user to manually write out _Tyroche Alar rolls 1d10, yielding [9] --> 9_ and no one would know the difference. 

I propose a unique icon (maybe a die?) that appears next to the line of text where the dice roll occurs to show the system actually did the roll.

I have provided an extremely crude mock-up:

![image](https://cloud.githubusercontent.com/assets/4184746/14722094/e03bc098-07d7-11e6-8d5b-b1d65329c8eb.png)

**Comment by etkirsch** [comment]
I'm all for this. There's actually a distinction on the backend (you can see which messages are rolls, messages, or emotes by going to `./api/messages`). I'd love to have some sort of glyphicon-ish die icon, do you have any suggestions?

**Comment by mlapaglia** [comment]
I found the message.html where an image can be applied. I forked the project and will try to get it working, first time with MEAN.

**Comment by etkirsch** [comment]
Awesome, you'll want to probably account for each of the following: 'roll', 'emote', 'dm, and 'message'. I haven't added the 'dm' one though... still not sure how best to show that the DM is narrating something

**Comment by mlapaglia** [comment]
I've added basic functionality for /roll with #28 , please check and if it's acceptable I'll add the others.
